# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sluglookup',
            field=models.SlugField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
