# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20171203_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sluglookup',
            field=models.SlugField(blank=True, max_length=15, unique=True),
        ),
    ]
