# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20171203_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='sluglookup',
        ),
        migrations.AddField(
            model_name='post',
            name='post_slug',
            field=models.SlugField(blank=True, max_length=15, unique=True),
        ),
    ]
